# Generated by Django 5.0.1 on 2026-09-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0010_delete_antiraggingaffidavit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='nature_of_grievance',
            field=models.CharField(choices=[('ragging', 'Ragging Related'), ('admission', 'Admission Related'), ('examination', 'Examination Related'), ('unfair_means', 'Unfair Means Related'), ('scholarship', 'Scholarship Related'), ('Other', 'Others')], max_length=100, verbose_name='Nature of Grievance'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Higher Authority'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='grievanceactionlog',
            name='status_changed_to',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Higher Authority'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='nature_of_grievance',
            field=models.CharField(choices=[('ragging', 'Ragging Related'), ('admission', 'Admission Related'), ('examination', 'Examination Related'), ('unfair_means', 'Unfair Means Related'), ('scholarship', 'Scholarship Related'), ('Other', 'Others')], max_length=100, verbose_name='Nature of Grievance'),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Higher Authority'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
